PARTICLE_GRAVITY = 0.3
PARTICLE_MIN_SPEED = 2
PARTICLE_MAX_SPEED = 6
PARTICLE_MIN_SIZE = 2
PARTICLE_MAX_SIZE = 5
PARTICLE_MIN_LIFETIME = 15
PARTICLE_MAX_LIFETIME = 30

TEXT_OUTLINE_OFFSET = 2

COOLDOWN_CIRCLE_START_ANGLE = -90

HEALTH_BAR_BORDER_PADDING = 2
HEALTH_BAR_BORDER_WIDTH = 2

STAR_DEFAULT_POINTS = 5

HEART_CIRCLE_OFFSET = 4
HEART_BORDER_WIDTH = 2

SWORD_SLASH_OUTER_WIDTH = 5
SWORD_SLASH_INNER_WIDTH = 2

SHIELD_ALPHA_DEFAULT = 128
SHIELD_INNER_ALPHA_DIVISOR = 2
SHIELD_BORDER_WIDTH = 3
